/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Escritorio;

import Utils.Session;

import java.awt.*;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import javax.swing.table.DefaultTableModel;
import Utils.Utils;
import com.google.gson.Gson;
import vo.Multiple.Pets;
import vo.Multiple.Reports;
import vo.Single.PackageInfo;
import vo.Single.Pet;
import vo.Single.Report;

/**
 *
 * @author Pepe Jiménez Narváez
 */
public class PetsUI extends javax.swing.JFrame {

    private Session session;
    Pets pets = new Pets();
    Reports reports = new Reports();
    DefaultTableModel petsModel;
    DefaultTableModel reportModel;
    final String server = "localhost";
    final int puerto = 4444;
    Socket socket;
    DataOutputStream salida;
    DataInputStream entrada;
    Utils utils = new Utils();
    Gson gson = new Gson();

    /**
     * Creates new form Owners
     */
    public PetsUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public PetsUI(Session session){
        initComponents();
        this.session = session;
        this.setLocationRelativeTo(null);
        fillSessionData();
        adaptTablePets();
        fillTablePets();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowControls = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        closeSession = new javax.swing.JLabel();
        ownersPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        petsPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        weightsPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        vaccinesPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        reportPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        loggedUserInfo = new javax.swing.JPanel();
        userName = new javax.swing.JLabel();
        clinicName = new javax.swing.JLabel();
        clinicImage = new javax.swing.JLabel();
        screen = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        petsTable = new javax.swing.JTable();
        userDetails = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        name = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        pathologies = new javax.swing.JLabel();
        search = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        accept = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        windowControls.setBackground(new java.awt.Color(22, 160, 133));
        windowControls.setMinimumSize(new java.awt.Dimension(120, 30));

        jPanel3.setBackground(new java.awt.Color(22, 160, 133));

        jLabel2.setBackground(new java.awt.Color(22, 160, 133));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Minimize.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(60, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(60, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(60, 30));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setBackground(new java.awt.Color(22, 160, 133));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout windowControlsLayout = new javax.swing.GroupLayout(windowControls);
        windowControls.setLayout(windowControlsLayout);
        windowControlsLayout.setHorizontalGroup(
            windowControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowControlsLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(windowControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(windowControlsLayout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 60, Short.MAX_VALUE)))
        );
        windowControlsLayout.setVerticalGroup(
            windowControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowControlsLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
            .addGroup(windowControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(windowControlsLayout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(windowControls);
        windowControls.setBounds(1080, 0, 120, 30);

        jPanel5.setBackground(new java.awt.Color(22, 160, 133));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(300, 0, 780, 30);

        Menu.setBackground(new java.awt.Color(22, 160, 133));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_pets_white_48dp_1.png"))); // NOI18N
        jLabel1.setText("PetsCare");

        closeSession.setBackground(new java.awt.Color(22, 160, 133));
        closeSession.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        closeSession.setForeground(new java.awt.Color(255, 255, 255));
        closeSession.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeSession.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_power_settings_new_white_36dp.png"))); // NOI18N
        closeSession.setText("Cerrar Sesión");
        closeSession.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeSession.setOpaque(true);
        closeSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeSessionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeSessionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeSessionMouseExited(evt);
            }
        });

        ownersPanel.setBackground(new java.awt.Color(22, 160, 133));
        ownersPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ownersPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ownersPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ownersPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ownersPanelMouseExited(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(22, 160, 133));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_people_white_36dp.png"))); // NOI18N
        jLabel3.setText("Propietarios");

        javax.swing.GroupLayout ownersPanelLayout = new javax.swing.GroupLayout(ownersPanel);
        ownersPanel.setLayout(ownersPanelLayout);
        ownersPanelLayout.setHorizontalGroup(
            ownersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ownersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ownersPanelLayout.setVerticalGroup(
            ownersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ownersPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addGap(4, 4, 4))
        );

        petsPanel.setBackground(new java.awt.Color(67, 213, 180));
        petsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setBackground(new java.awt.Color(22, 160, 133));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_pets_white_36dp.png"))); // NOI18N
        jLabel4.setText("Mascotas");

        javax.swing.GroupLayout petsPanelLayout = new javax.swing.GroupLayout(petsPanel);
        petsPanel.setLayout(petsPanelLayout);
        petsPanelLayout.setHorizontalGroup(
            petsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(petsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        petsPanelLayout.setVerticalGroup(
            petsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(petsPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addGap(4, 4, 4))
        );

        weightsPanel.setBackground(new java.awt.Color(22, 160, 133));
        weightsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        weightsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                weightsPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                weightsPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                weightsPanelMouseExited(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(22, 160, 133));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/weight-kilogram.png"))); // NOI18N
        jLabel11.setText("Peso");

        javax.swing.GroupLayout weightsPanelLayout = new javax.swing.GroupLayout(weightsPanel);
        weightsPanel.setLayout(weightsPanelLayout);
        weightsPanelLayout.setHorizontalGroup(
            weightsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weightsPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        weightsPanelLayout.setVerticalGroup(
            weightsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weightsPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel11)
                .addGap(4, 4, 4))
        );

        vaccinesPanel.setBackground(new java.awt.Color(22, 160, 133));
        vaccinesPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vaccinesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vaccinesPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vaccinesPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vaccinesPanelMouseExited(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(22, 160, 133));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/needle.png"))); // NOI18N
        jLabel12.setText("Vacunas");

        javax.swing.GroupLayout vaccinesPanelLayout = new javax.swing.GroupLayout(vaccinesPanel);
        vaccinesPanel.setLayout(vaccinesPanelLayout);
        vaccinesPanelLayout.setHorizontalGroup(
            vaccinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vaccinesPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vaccinesPanelLayout.setVerticalGroup(
            vaccinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vaccinesPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel12)
                .addGap(4, 4, 4))
        );

        reportPanel.setBackground(new java.awt.Color(22, 160, 133));
        reportPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportPanelMouseExited(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(22, 160, 133));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file-document.png"))); // NOI18N
        jLabel13.setText("Informes Diarios");

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel13)
                .addGap(4, 4, 4))
        );

        loggedUserInfo.setBackground(new java.awt.Color(22, 160, 133));

        userName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setText("Bienvenido ");

        clinicName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clinicName.setForeground(new java.awt.Color(255, 255, 255));
        clinicName.setText("Nombre clínica");

        clinicImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clinicImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_pets_white_48dp.png"))); // NOI18N

        javax.swing.GroupLayout loggedUserInfoLayout = new javax.swing.GroupLayout(loggedUserInfo);
        loggedUserInfo.setLayout(loggedUserInfoLayout);
        loggedUserInfoLayout.setHorizontalGroup(
            loggedUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loggedUserInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loggedUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loggedUserInfoLayout.createSequentialGroup()
                        .addGroup(loggedUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userName)
                            .addComponent(clinicName))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(clinicImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        loggedUserInfoLayout.setVerticalGroup(
            loggedUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loggedUserInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userName)
                .addGap(18, 18, 18)
                .addComponent(clinicName)
                .addGap(18, 18, 18)
                .addComponent(clinicImage, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeSession, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ownersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(petsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(weightsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vaccinesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reportPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loggedUserInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(ownersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(petsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(weightsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(vaccinesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(reportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(loggedUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closeSession, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        getContentPane().add(Menu);
        Menu.setBounds(0, 0, 300, 700);

        screen.setBackground(new java.awt.Color(26, 188, 156));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        petsTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        petsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        petsTable.setIntercellSpacing(new java.awt.Dimension(1, 5));
        petsTable.setRowHeight(24);
        petsTable.setSelectionBackground(new java.awt.Color(51, 102, 255));
        petsTable.setShowHorizontalLines(false);
        petsTable.setShowVerticalLines(false);
        petsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                petsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(petsTable);

        userDetails.setBackground(new java.awt.Color(26, 188, 156));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre Completo");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Edad");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Patologías");

        reportTable.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        reportTable.setSelectionBackground(new java.awt.Color(51, 102, 255));
        reportTable.setShowHorizontalLines(false);
        reportTable.setShowVerticalLines(false);
        reportTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(reportTable);

        name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name.setText(" ");

        age.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        age.setForeground(new java.awt.Color(255, 255, 255));
        age.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        age.setText(" ");

        pathologies.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pathologies.setForeground(new java.awt.Color(255, 255, 255));
        pathologies.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pathologies.setText(" ");

        javax.swing.GroupLayout userDetailsLayout = new javax.swing.GroupLayout(userDetails);
        userDetails.setLayout(userDetailsLayout);
        userDetailsLayout.setHorizontalGroup(
            userDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userDetailsLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(userDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(age, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pathologies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        userDetailsLayout.setVerticalGroup(
            userDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userDetailsLayout.createSequentialGroup()
                .addGroup(userDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userDetailsLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(age)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pathologies))
                    .addGroup(userDetailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        search.setBackground(new java.awt.Color(26, 188, 156));

        searchField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchFieldKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_search_white_24dp.png"))); // NOI18N
        jLabel9.setText("Buscar");

        accept.setBackground(new java.awt.Color(22, 160, 133));
        accept.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        accept.setForeground(new java.awt.Color(255, 255, 255));
        accept.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accept.setText("Aceptar");
        accept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accept.setOpaque(true);
        accept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acceptMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                acceptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                acceptMouseExited(evt);
            }
        });
        accept.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                acceptKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout searchLayout = new javax.swing.GroupLayout(search);
        search.setLayout(searchLayout);
        searchLayout.setHorizontalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(accept, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        searchLayout.setVerticalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))
                    .addComponent(accept, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout screenLayout = new javax.swing.GroupLayout(screen);
        screen.setLayout(screenLayout);
        screenLayout.setHorizontalGroup(
            screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, screenLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(userDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addGroup(screenLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        screenLayout.setVerticalGroup(
            screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screenLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(screen);
        screen.setBounds(300, 30, 900, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jPanel3.setBackground(new java.awt.Color(26, 188, 156));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jPanel3.setBackground(new java.awt.Color(22, 160, 133));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jPanel4.setBackground(new java.awt.Color(238, 17, 17));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jPanel4.setBackground(new java.awt.Color(22, 160, 133));
    }//GEN-LAST:event_jLabel5MouseExited

    private void weightsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_weightsPanelMouseEntered
        weightsPanel.setBackground(new java.awt.Color(26, 188, 156));    }//GEN-LAST:event_weightsPanelMouseEntered

    private void weightsPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_weightsPanelMouseExited
        weightsPanel.setBackground(new java.awt.Color(22, 160, 133));
    }//GEN-LAST:event_weightsPanelMouseExited

    private void vaccinesPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaccinesPanelMouseEntered
        vaccinesPanel.setBackground(new java.awt.Color(26, 188, 156));    }//GEN-LAST:event_vaccinesPanelMouseEntered

    private void vaccinesPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaccinesPanelMouseExited
        vaccinesPanel.setBackground(new java.awt.Color(22, 160, 133));
    }//GEN-LAST:event_vaccinesPanelMouseExited

    private void reportPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportPanelMouseEntered
        reportPanel.setBackground(new java.awt.Color(26, 188, 156));    }//GEN-LAST:event_reportPanelMouseEntered

    private void reportPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportPanelMouseExited
        reportPanel.setBackground(new java.awt.Color(22, 160, 133));
    }//GEN-LAST:event_reportPanelMouseExited

    private void closeSessionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeSessionMouseEntered
        closeSession.setBackground(new java.awt.Color(238, 17, 17));
    }//GEN-LAST:event_closeSessionMouseEntered

    private void closeSessionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeSessionMouseExited
        closeSession.setBackground(new java.awt.Color(22, 160, 133));
    }//GEN-LAST:event_closeSessionMouseExited

    private void ownersPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ownersPanelMouseEntered
        ownersPanel.setBackground(new java.awt.Color(26, 188, 156));
    }//GEN-LAST:event_ownersPanelMouseEntered

    private void ownersPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ownersPanelMouseExited
        ownersPanel.setBackground(new java.awt.Color(22, 160, 133));
    }//GEN-LAST:event_ownersPanelMouseExited

    private void weightsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_weightsPanelMouseClicked
        WeightsUI weightsUI = new WeightsUI();
        weightsUI.setSession(session);
        weightsUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_weightsPanelMouseClicked

    private void vaccinesPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaccinesPanelMouseClicked
        VaccinesUI vaccinesUI = new VaccinesUI();
        vaccinesUI.setSession(session);
        vaccinesUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_vaccinesPanelMouseClicked

    private void reportPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportPanelMouseClicked
        ReportsUI reportsUI = new ReportsUI();
        reportsUI.setSession(session);
        reportsUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_reportPanelMouseClicked

    private void ownersPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ownersPanelMouseClicked
        OwnersUI ownersUI = new OwnersUI(session);
        ownersUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ownersPanelMouseClicked

    private void closeSessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeSessionMouseClicked
        LogOut logOut = new LogOut(this, rootPaneCheckingEnabled);
        logOut.setVisible(true);
    }//GEN-LAST:event_closeSessionMouseClicked

    private void petsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petsTableMouseClicked
        session.setSelectedPet(pets.getPetById((int) petsModel.getValueAt(petsTable.getSelectedRow(), 5)));
        name.setText(session.getSelectedPet().getName());
        age.setText(session.getSelectedPet().getAge() + " Años");
        pathologies.setText(session.getSelectedPet().getPathologies());

        String petId = petsModel.getValueAt(petsTable.getSelectedRow(), 5).toString();
        PackageInfo packageInfo = new PackageInfo(Utils.OBTENER_INFORMES_MASCOTA, petId);
        System.out.println("*******************************************************************");
        System.out.println("CONSULTA A REALIZAR: " + packageInfo.getTipo());
        System.out.println("Objeto dentro: " + packageInfo.getObjeto());
        System.out.println("*******************************************************************");
        try {
            socket = new Socket(server, puerto);
            entrada = new DataInputStream(socket.getInputStream());
            salida = new DataOutputStream(socket.getOutputStream());
            salida.writeUTF(gson.toJson(packageInfo));
            System.out.println("*******************************************************************");
            System.out.println("PAQUETE ENVIADO AL SERVIDOR");
            System.out.println("*******************************************************************");
            packageInfo = gson.fromJson(entrada.readUTF(), PackageInfo.class);
            reports = gson.fromJson(packageInfo.getObjeto(), Reports.class);
            System.out.println("*******************************************************************");
            System.out.println("PAQUETE RECIBIDO DEL SERVIDOR");
            System.out.println("*******************************************************************");
            System.out.println("*******************************************************************");
            System.out.println("RESPUESTA: " + packageInfo.getTipo() + " : " + packageInfo.getObjeto());
            System.out.println("*******************************************************************");
            session.setSelectedPet(pets.getPetById((int) petsModel.getValueAt(petsTable.getSelectedRow(), 5)));
            adaptTableReport();
            fillTableReport();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_petsTableMouseClicked

    private void reportTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportTableMouseClicked
        /*session.setSelectedPet(pets.getPetById((int) petsModel.getValueAt(petsTable.getSelectedRow(), 2)));
        System.out.println("Pet id seleccionado " + session.getSelectedPet().getPetId());
        PetsUI petsUI = new PetsUI(session);*/
    }//GEN-LAST:event_reportTableMouseClicked

    private void searchFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            filterByField();
        }
    }//GEN-LAST:event_searchFieldKeyPressed

    private void acceptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptMouseClicked
        filterByField();
    }//GEN-LAST:event_acceptMouseClicked

    private void acceptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptMouseEntered
        accept.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_acceptMouseEntered

    private void acceptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptMouseExited
        accept.setBorder(null);
    }//GEN-LAST:event_acceptMouseExited

    private void acceptKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acceptKeyPressed

    }//GEN-LAST:event_acceptKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PetsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel accept;
    private javax.swing.JLabel age;
    private javax.swing.JLabel clinicImage;
    private javax.swing.JLabel clinicName;
    private javax.swing.JLabel closeSession;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel loggedUserInfo;
    private javax.swing.JLabel name;
    private javax.swing.JPanel ownersPanel;
    private javax.swing.JLabel pathologies;
    private javax.swing.JPanel petsPanel;
    private javax.swing.JTable petsTable;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JTable reportTable;
    private javax.swing.JPanel screen;
    private javax.swing.JPanel search;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel userDetails;
    private javax.swing.JLabel userName;
    private javax.swing.JPanel vaccinesPanel;
    private javax.swing.JPanel weightsPanel;
    private javax.swing.JPanel windowControls;
    // End of variables declaration//GEN-END:variables

    public Session getSession() {
        return session;
    }

    public void setSession(Session session) {
        this.session = session;
    }

    private void fillTablePets() {
        try {
            socket = new Socket(server, puerto);
            entrada = new DataInputStream(socket.getInputStream());
            salida = new DataOutputStream(socket.getOutputStream());
            PackageInfo packageInfo = new PackageInfo(Utils.OBTENER_MASCOTAS_CLINICA, gson.toJson(session.getClinic()));
            System.out.println("*******************************************************************");
            System.out.println("CONSULTA A REALIZAR: " + packageInfo.getTipo());
            System.out.println("Objeto dentro: " + packageInfo.getObjeto());
            System.out.println("*******************************************************************");
            salida.writeUTF(gson.toJson(packageInfo));
            System.out.println("*******************************************************************");
            System.out.println("PAQUETE ENVIADO AL SERVIDOR");
            System.out.println("*******************************************************************");
            packageInfo = gson.fromJson(entrada.readUTF(), PackageInfo.class);
            System.out.println("*******************************************************************");
            System.out.println("PAQUETE RECIBIDO DEL SERVIDOR");
            System.out.println("*******************************************************************");
            System.out.println("*******************************************************************");
            System.out.println("RESPUESTA: " + packageInfo.getTipo() + " : " + packageInfo.getObjeto());
            System.out.println("*******************************************************************");
            pets = gson.fromJson(packageInfo.getObjeto(), Pets.class);
        } catch (IOException ex) {

        }
        petsModel.setRowCount(0);
        petsModel = (DefaultTableModel) petsTable.getModel();

        int row = 0;
        for (Pet pet : pets) {
            Report report = getLastReportId(pet.getPetId());
            String lastVisit = (report != null)?utils.formatDate(report.getDate()):"";
            Object[] aux = {pet.getName(), pet.getAge(), pet.renderType(pet.getPetType()), getOwnerName(pet.getOwnerId()), lastVisit, pet.getPetId()};
            petsModel.addRow(aux);
            if(session.getSelectedPet() != null && session.getSelectedPet().getPetId() == pet.getPetId()){
                petsTable.setRowSelectionInterval(row,row);
            }
            row++;
        }
    }

    private void adaptTablePets() {
        String titulos[] = {"Nombre", "Edad", "Tipo", "Propietario","Última Visita" ,"petId"};
        petsModel = new DefaultTableModel(null, titulos) {
            //hace la tabla no editable
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        petsTable.setModel(petsModel);
        petsTable.getColumnModel().getColumn(5).setMinWidth(0);
        petsTable.getColumnModel().getColumn(5).setMaxWidth(0);
        petsTable.getColumnModel().getColumn(5).setWidth(0);
        petsTable.getColumnModel().getColumn(1).setMaxWidth(45);
        petsTable.getTableHeader().setFont(new java.awt.Font("Segoe UI", 0, 14));
        petsTable.setAutoCreateRowSorter(true);
    }

    public void filterByField() {
        if (searchField.getText().length() != 0) {
            petsModel.setRowCount(0);
            petsModel = (DefaultTableModel) petsTable.getModel();
            for (Pet pet : pets) {
                Report report = getLastReportId(pet.getPetId());
                String lastVisit = (report != null)?utils.formatDate(report.getDate()):"";
                Object[] aux = {pet.getName(), pet.getAge(), pet.renderType(pet.getPetType()), getOwnerName(pet.getOwnerId()), lastVisit, pet.getPetId()};
                if (pet.getName().toLowerCase().contains(searchField.getText().toLowerCase())) {
                    petsModel.addRow(aux);
                    continue;
                }
            }
        } else {
            fillTablePets();
        }
    }

    private void fillSessionData(){
        userName.setText(userName.getText() + session.getLoggedUser().getName() + " " + session.getLoggedUser().getSurname());
        clinicName.setText(session.getClinic().getName());
    }

    private String getOwnerName(int id){
        try {
            socket = new Socket(server, puerto);
            entrada = new DataInputStream(socket.getInputStream());
            salida = new DataOutputStream(socket.getOutputStream());
            PackageInfo packageInfo = new PackageInfo(Utils.OBTENER_NOMBRE_PROPIETARIO_ID, gson.toJson(id));
            System.out.println("*******************************************************************");
            System.out.println("CONSULTA A REALIZAR: " + packageInfo.getTipo());
            System.out.println("Objeto dentro: " + packageInfo.getObjeto());
            System.out.println("*******************************************************************");
            salida.writeUTF(gson.toJson(packageInfo));
            System.out.println("*******************************************************************");
            System.out.println("PAQUETE ENVIADO AL SERVIDOR");
            System.out.println("*******************************************************************");
            packageInfo = gson.fromJson(entrada.readUTF(), PackageInfo.class);
            System.out.println("*******************************************************************");
            System.out.println("PAQUETE RECIBIDO DEL SERVIDOR");
            System.out.println("*******************************************************************");
            System.out.println("*******************************************************************");
            System.out.println("RESPUESTA: " + packageInfo.getTipo() + " : " + packageInfo.getObjeto());
            System.out.println("*******************************************************************");
            return gson.fromJson(packageInfo.getObjeto(), String.class);
        } catch (IOException ex) {

        }
        return "Desconocido";
    }

    private Report getLastReportId(int petId) {
        try {
            socket = new Socket(server, puerto);
            entrada = new DataInputStream(socket.getInputStream());
            salida = new DataOutputStream(socket.getOutputStream());
            PackageInfo packageInfo = new PackageInfo(Utils.OBTENER_ULTIMO_INFORME, gson.toJson(petId));
            System.out.println("*******************************************************************");
            System.out.println("CONSULTA A REALIZAR: " + packageInfo.getTipo());
            System.out.println("Objeto dentro: " + packageInfo.getObjeto());
            System.out.println("*******************************************************************");
            salida.writeUTF(gson.toJson(packageInfo));
            System.out.println("*******************************************************************");
            System.out.println("PAQUETE ENVIADO AL SERVIDOR");
            System.out.println("*******************************************************************");
            packageInfo = gson.fromJson(entrada.readUTF(), PackageInfo.class);
            System.out.println("*******************************************************************");
            System.out.println("PAQUETE RECIBIDO DEL SERVIDOR");
            System.out.println("*******************************************************************");
            System.out.println("*******************************************************************");
            System.out.println("RESPUESTA: " + packageInfo.getTipo() + " : " + packageInfo.getObjeto());
            System.out.println("*******************************************************************");

            return gson.fromJson(packageInfo.getObjeto(), Report.class);
        } catch (IOException ex) {

        }
        return null;
    }

    private void adaptTableReport() {
        String titulos[] = {"Fecha", "Motivo"};
        reportModel = new DefaultTableModel(null, titulos) {
            //hace la tabla no editable
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        reportTable.setModel(reportModel);
        reportTable.getTableHeader().setFont(new java.awt.Font("Segoe UI", 0, 14));
        reportTable.setAutoCreateRowSorter(true);
    }

    private void fillTableReport() {
        reportModel.setRowCount(0);
        reportModel = (DefaultTableModel) reportTable.getModel();

        for (Report report : reports) {
            Object[] aux = {report.getDate(), report.getSummary(), report.getPetId()};
            reportModel.addRow(aux);
        }
    }

}
