/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Escritorio;

import Utils.MockDao;
import Utils.Utils;

import java.awt.Font;
import java.awt.Frame;
import java.awt.font.TextAttribute;
import java.io.*;
import java.net.Socket;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import com.google.gson.Gson;
import vo.Single.Clinic;
import vo.Single.PackageInfo;
import vo.Single.User;

/**
 * @author jjimenez
 */
public class SingUp extends javax.swing.JFrame {

    final String server = "localhost";
    final int puerto = 4444;
    Socket socket;
    DataOutputStream salida;
    DataInputStream entrada;
    Utils utils = new Utils();
    ArrayList<Clinic> clinicsArray;
    ArrayList<Integer> clinicsId;
    Gson gson = new Gson();

    //MOCK
    MockDao mockDao = new MockDao();

    /**
     * Creates new form Main
     */
    public SingUp() {
        initComponents();
        errorUsername.setText(" ");
        errorName.setText(" ");
        errorSurname.setText(" ");
        errorMail.setText(" ");
        errorPass1.setText(" ");
        errorPass2.setText(" ");
        errorPhone.setText(" ");
        errorClinic.setText(" ");
        fillClinicCombo(clinicsArray);
        this.setLocationRelativeTo(null);
        try {
            socket = new Socket(server, puerto);
            entrada = new DataInputStream(socket.getInputStream());
            salida = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowControls = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        password = new javax.swing.JPasswordField();
        user = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        surname = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        clinic = new javax.swing.JComboBox<>();
        errorUsername = new javax.swing.JLabel();
        errorName = new javax.swing.JLabel();
        errorPhone = new javax.swing.JLabel();
        errorSurname = new javax.swing.JLabel();
        errorClinic = new javax.swing.JLabel();
        errorMail = new javax.swing.JLabel();
        errorPass1 = new javax.swing.JLabel();
        errorPass2 = new javax.swing.JLabel();
        password1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        accept = new javax.swing.JLabel();
        logIn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(500, 700));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        windowControls.setBackground(new java.awt.Color(22, 160, 133));
        windowControls.setMinimumSize(new java.awt.Dimension(120, 30));

        jPanel3.setBackground(new java.awt.Color(22, 160, 133));

        jLabel2.setBackground(new java.awt.Color(22, 160, 133));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Minimize.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(60, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(60, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(60, 30));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setBackground(new java.awt.Color(22, 160, 133));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout windowControlsLayout = new javax.swing.GroupLayout(windowControls);
        windowControls.setLayout(windowControlsLayout);
        windowControlsLayout.setHorizontalGroup(
                windowControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(windowControlsLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(windowControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(windowControlsLayout.createSequentialGroup()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 60, Short.MAX_VALUE)))
        );
        windowControlsLayout.setVerticalGroup(
                windowControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(windowControlsLayout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))
                        .addGroup(windowControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(windowControlsLayout.createSequentialGroup()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(windowControls);
        windowControls.setBounds(380, 0, 120, 30);

        header.setBackground(new java.awt.Color(22, 160, 133));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_pets_white_48dp_1.png"))); // NOI18N
        jLabel1.setText("PetsCare");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
                headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(jLabel1)
                                .addGap(175, 175, 175))
        );
        headerLayout.setVerticalGroup(
                headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addContainerGap())
        );

        getContentPane().add(header);
        header.setBounds(0, 0, 500, 70);

        body.setBackground(new java.awt.Color(26, 188, 156));

        jPanel1.setBackground(new java.awt.Color(26, 188, 156));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 100));

        password.setBackground(new java.awt.Color(26, 188, 156));
        password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        password.setText("password");
        password.setToolTipText("Contraseña");
        password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });

        user.setBackground(new java.awt.Color(26, 188, 156));
        user.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        user.setText("Usuario");
        user.setToolTipText("Usuario");
        user.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                userFocusLost(evt);
            }
        });
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });

        mail.setBackground(new java.awt.Color(26, 188, 156));
        mail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mail.setForeground(new java.awt.Color(255, 255, 255));
        mail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mail.setText("E-mail");
        mail.setToolTipText("E-mail");
        mail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                mailFocusLost(evt);
            }
        });
        mail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mailMouseClicked(evt);
            }
        });

        name.setBackground(new java.awt.Color(26, 188, 156));
        name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        name.setText("Nombre");
        name.setToolTipText("Nombre");
        name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameMouseClicked(evt);
            }
        });

        surname.setBackground(new java.awt.Color(26, 188, 156));
        surname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        surname.setForeground(new java.awt.Color(255, 255, 255));
        surname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        surname.setText("Apellidos");
        surname.setToolTipText("Apellidos");
        surname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        surname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                surnameFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                surnameFocusLost(evt);
            }
        });
        surname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                surnameMouseClicked(evt);
            }
        });

        phone.setBackground(new java.awt.Color(26, 188, 156));
        phone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        phone.setText("Teléfono");
        phone.setToolTipText("Teléfono");
        phone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneFocusLost(evt);
            }
        });
        phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoneMouseClicked(evt);
            }
        });

        clinic.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clinic.setBorder(null);
        clinic.setOpaque(false);

        errorUsername.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        errorUsername.setForeground(new java.awt.Color(255, 0, 0));
        errorUsername.setText("El nombre de usuario ya existe.");

        errorName.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        errorName.setForeground(new java.awt.Color(255, 0, 0));
        errorName.setText("Por favor complete el campo");

        errorPhone.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        errorPhone.setForeground(new java.awt.Color(255, 0, 0));
        errorPhone.setText("Por favor complete el campo");

        errorSurname.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        errorSurname.setForeground(new java.awt.Color(255, 0, 0));
        errorSurname.setText("Por favor complete el campo");

        errorClinic.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        errorClinic.setForeground(new java.awt.Color(255, 0, 0));
        errorClinic.setText("Por favor complete el campo");

        errorMail.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        errorMail.setForeground(new java.awt.Color(255, 0, 0));
        errorMail.setText("Por favor complete el campo");

        errorPass1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        errorPass1.setForeground(new java.awt.Color(255, 0, 0));
        errorPass1.setText("Por favor complete el campo");

        errorPass2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        errorPass2.setForeground(new java.awt.Color(255, 0, 0));
        errorPass2.setText("Las contraseñas no coinciden");

        password1.setBackground(new java.awt.Color(26, 188, 156));
        password1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        password1.setForeground(new java.awt.Color(255, 255, 255));
        password1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        password1.setText("passworx");
        password1.setToolTipText("Contraseña");
        password1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        password1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password1FocusGained(evt);
            }
        });
        password1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                password1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Clínica");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(mail, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(password, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(clinic, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(errorUsername)
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(user, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(surname, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                                                                                .addComponent(phone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                                                                        .addComponent(errorName)
                                                                        .addComponent(errorPhone)
                                                                        .addComponent(errorSurname)))
                                                        .addComponent(password1, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(98, 98, 98))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(errorPass1)
                                                        .addComponent(errorMail))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(errorClinic)
                                                        .addComponent(errorPass2))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(errorUsername)
                                .addGap(8, 8, 8)
                                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(errorName)
                                .addGap(4, 4, 4)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(errorSurname)
                                .addGap(4, 4, 4)
                                .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(errorPhone)
                                .addGap(4, 4, 4)
                                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(errorClinic)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(clinic)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(errorMail)
                                .addGap(4, 4, 4)
                                .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(errorPass1)
                                .addGap(4, 4, 4)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(errorPass2)
                                .addGap(4, 4, 4)
                                .addComponent(password1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(26, Short.MAX_VALUE))
        );

        accept.setBackground(new java.awt.Color(22, 160, 133));
        accept.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        accept.setForeground(new java.awt.Color(255, 255, 255));
        accept.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accept.setText("Aceptar");
        accept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accept.setOpaque(true);
        accept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acceptMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                acceptMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                acceptMouseExited(evt);
            }
        });

        logIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logIn.setForeground(new java.awt.Color(255, 255, 255));
        logIn.setText("¿Tienes ya una cuenta? Haz click para iniciar sesión.");
        logIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logInMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logInMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                logInMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
                bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                        .addGroup(bodyLayout.createSequentialGroup()
                                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(bodyLayout.createSequentialGroup()
                                                .addGap(95, 95, 95)
                                                .addComponent(logIn))
                                        .addGroup(bodyLayout.createSequentialGroup()
                                                .addGap(185, 185, 185)
                                                .addComponent(accept, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(95, 95, 95))
        );
        bodyLayout.setVerticalGroup(
                bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bodyLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(accept, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(logIn)
                                .addContainerGap())
        );

        getContentPane().add(body);
        body.setBounds(0, 70, 500, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void acceptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptMouseEntered
        accept.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_acceptMouseEntered

    private void acceptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptMouseExited
        accept.setBorder(null);
    }//GEN-LAST:event_acceptMouseExited

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        user.selectAll();
    }//GEN-LAST:event_userMouseClicked

    private void userFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusLost
        if (user.getText().equals("")) {
            user.setText("Usuario");
        }
    }//GEN-LAST:event_userFocusLost

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        password.selectAll();
    }//GEN-LAST:event_passwordMouseClicked

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        password.selectAll();
    }//GEN-LAST:event_passwordFocusGained

    private void mailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusLost
        mail.selectAll();
    }//GEN-LAST:event_mailFocusLost

    private void mailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mailMouseClicked
        mail.selectAll();
    }//GEN-LAST:event_mailMouseClicked

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        name.selectAll();
    }//GEN-LAST:event_nameFocusLost

    private void nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseClicked
        name.selectAll();
    }//GEN-LAST:event_nameMouseClicked

    private void surnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_surnameFocusLost
        surname.selectAll();
    }//GEN-LAST:event_surnameFocusLost

    private void surnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_surnameMouseClicked
        surname.selectAll();
    }//GEN-LAST:event_surnameMouseClicked

    private void phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusLost
        phone.selectAll();
    }//GEN-LAST:event_phoneFocusLost

    private void phoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneMouseClicked
        phone.selectAll();
    }//GEN-LAST:event_phoneMouseClicked

    private void logInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInMouseClicked
        LogIn logInUI = new LogIn();
        logInUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logInMouseClicked

    private void logInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInMouseEntered
        Font font = logIn.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        logIn.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_logInMouseEntered

    private void logInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInMouseExited
        logIn.setFont(new java.awt.Font("Segoe UI", 0, 14));
    }//GEN-LAST:event_logInMouseExited

    private void password1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password1FocusGained
        password1.selectAll();
    }//GEN-LAST:event_password1FocusGained

    private void password1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_password1MouseClicked
        password1.selectAll();
    }//GEN-LAST:event_password1MouseClicked

    private void acceptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptMouseClicked
        try {
            User usuarioNew = comprobarDatosRegistro();
            if (usuarioNew != null) {
                PackageInfo packageInfo = new PackageInfo(Utils.INSERTAR_USUARIO, gson.toJson(usuarioNew));
                    salida.writeUTF(gson.toJson(packageInfo));
                    System.out.println("Usuario insertado");

                JOptionPane.showMessageDialog(this, "Usuario registrado correctamente.");
                LogIn logIn = new LogIn();
                logIn.setVisible(true);
                this.setVisible(false);
            }
        } catch (NoSuchAlgorithmException | IOException ex) {
            Logger.getLogger(SingUp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_acceptMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jPanel3.setBackground(new java.awt.Color(26, 188, 156));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jPanel3.setBackground(new java.awt.Color(22, 160, 133));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jPanel4.setBackground(new java.awt.Color(238, 17, 17));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jPanel4.setBackground(new java.awt.Color(22, 160, 133));
    }//GEN-LAST:event_jLabel5MouseExited

    private void userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusGained
        user.selectAll();
    }//GEN-LAST:event_userFocusGained

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        name.selectAll();
    }//GEN-LAST:event_nameFocusGained

    private void surnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_surnameFocusGained
        surname.selectAll();
    }//GEN-LAST:event_surnameFocusGained

    private void phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusGained
        phone.selectAll();
    }//GEN-LAST:event_phoneFocusGained

    private void mailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusGained
        mail.selectAll();
    }//GEN-LAST:event_mailFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SingUp().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accept;
    private javax.swing.JPanel body;
    private javax.swing.JComboBox<Clinic> clinic;
    private javax.swing.JLabel errorClinic;
    private javax.swing.JLabel errorMail;
    private javax.swing.JLabel errorName;
    private javax.swing.JLabel errorPass1;
    private javax.swing.JLabel errorPass2;
    private javax.swing.JLabel errorPhone;
    private javax.swing.JLabel errorSurname;
    private javax.swing.JLabel errorUsername;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel logIn;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField password1;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField surname;
    private javax.swing.JTextField user;
    private javax.swing.JPanel windowControls;
    // End of variables declaration//GEN-END:variables

    private User comprobarDatosRegistro() throws NoSuchAlgorithmException {
        errorUsername.setText(" ");
        errorName.setText(" ");
        errorSurname.setText(" ");
        errorMail.setText(" ");
        errorPass1.setText(" ");
        errorPass2.setText(" ");
        errorPhone.setText(" ");
        boolean flagCheck = false;
        boolean userCheck = false;
        boolean userExistCheck = false;
        boolean nameCheck = false;
        boolean surNameCheck = false;
        boolean phoneCheck = false;
        boolean clinicCheck = false;
        boolean mailCheck = false;
        boolean mailExistCheck = false;
        boolean passCheck = false;

        if (user.getText().isEmpty() || user.getText().equals("Usuario")) {
            userCheck = false;
            errorUsername.setText("Por favor completa el campo");

        } else {
            userCheck = true;
            System.out.println("USUARIO RELLENO OK");
        }
        if (name.getText().isEmpty() || name.getText().equals("Nombre")) {
            nameCheck = false;
            errorName.setText("Por favor completa el campo");
        } else {
            nameCheck = true;
            System.out.println("NOMBRE RELLENO OK");
        }
        if (surname.getText().isEmpty() || surname.getText().equals("Apellidos")) {
            surNameCheck = false;
            errorSurname.setText("Por favor completa el campo");
        } else {
            surNameCheck = true;
            System.out.println("APELLIDO RELLENO OK");
        }
        if (!comprobarFormatoTelefono(phone.getText())) {
            phoneCheck = false;
            errorPhone.setText("Por favor comprueba el formato(Ej: 900900900)");
        } else {
            phoneCheck = true;
            System.out.println("TELEFONO CORRECTO OK");
        }
        if (clinic.getSelectedIndex() == 0) {
            clinicCheck = false;
            errorClinic.setText("Por favor selecciona tu clinica");
        } else {
            clinicCheck = true;
            System.out.println("CLINICA OK");
        }
        if (!comprobarFormatoEmail(mail.getText())) {
            mailCheck = false;
            errorMail.setText("Por favor comprueba el formato(Ej: [dirección]@[dominio]");
        } else {
            mailCheck = true;
            System.out.println("MAIL CORRECTO OK");
        }
        if (password.getText().isEmpty() || password.getText().equals("password")) {
            passCheck = false;
            errorPass1.setText("Por favor completa el campo");
        } else if (password1.getText().isEmpty() || password1.getText().equals("passworx")) {
            passCheck = false;
            errorPass2.setText("Por favor completa el campo");
        } else if (!password.getText().equals(password1.getText())) {
            passCheck = false;
            errorPass1.setText("Las contraseñas no coinciden");
        } else {
            System.out.println("CONTRASEÑAS COMPLETAS E IGUALES OK");
            passCheck = true;
        }
        User usuarioOut = new User(user.getText(), utils.Encrypt(password.getText()), name.getText(), surname.getText(), mail.getText(), phone.getText(), 1, 1, 0);
        PackageInfo packageInfo = new PackageInfo(Utils.COMPROBAR_USUARIO, gson.toJson(usuarioOut));
        System.out.println("Paquete enviado " + gson.toJson(packageInfo));
        try {
            salida.writeUTF(gson.toJson(packageInfo));
            packageInfo = gson.fromJson(entrada.readUTF(), PackageInfo.class);
            User usuarioIn = gson.fromJson(packageInfo.getObjeto(), User.class);
            System.out.println("Paquete recibido " + gson.toJson(packageInfo));

            if (usuarioIn.getUsername() == null) {
                errorUsername.setText("El nombre de usuario ya existe, por favor seleccione otro");
                userExistCheck = false;
            } else {
                System.out.println("USUARIO NO DUPLICADO OK");
                userExistCheck = true;
            }

            if (usuarioIn.getMail() == null) {
                errorMail.setText("El email ya se encuentra registrado");
            } else {
                System.out.println("EMAIL NO DUPLICADO OK");
                mailExistCheck = true;
            }

            User usuarioNew;
            if (userCheck && nameCheck && surNameCheck && phoneCheck && clinicCheck && mailCheck && passCheck && userExistCheck && mailExistCheck) {
                usuarioNew = new User(user.getText(), utils.Encrypt(password.getText()), name.getText(), surname.getText(), mail.getText(), phone.getText(), 1, 1, 0);
                System.out.println("FORMULARIO CORRECTO");
                return  usuarioNew;
            }
            System.out.println("FORMULARIO INCORRECTO");
            return null;
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }

    public boolean comprobarFormatoTelefono(String phone) {
        if (phone.length() == 9 && phone.matches("^\\d+$")) {
            System.out.println("TELEFONO CUMPLE PATRON");
            return true;
        }
        return false;
    }

    public boolean comprobarFormatoEmail(String mail) {
        if (mail.matches("^(.+)@(.+)$")) {
            System.out.println("MAIL CUMPLE PATRON");
            return true;
        }
        return false;
    }

    private void fillClinicCombo(ArrayList<Clinic> clinicsArray) {
        clinicsArray = mockDao.getClinics();
        System.out.println("Tamaño del clinicsArray = " + clinicsArray.size());
        for (Clinic next : clinicsArray) {
            clinic.addItem(next);
        }
        this.clinicsArray = clinicsArray;
    }


}
